artifact.groupId=${project.groupId}
artifact.artifactId=${project.artifactId}
artifact.version=${project.version}
git.commit.id=${git.commit.id.full}
git.commit.id.abbrev=${git.commit.id.abbrev}
git.branch=${git.branch}
git.dirty=${git.dirty}
build.time=${maven.build.timestamp}
